variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

bitstream:
  stage: build
  image: vivado2018:2018.3
  script:
    - env
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source build.tcl thinpad_top.xpr

  artifacts:
    paths:
      - thinpad_top.runs/impl_1/thinpad_top.bit

test_on_cloud:
  stage: test
  image: ubuntu:16.04 
  before_script:
    - pushd Thinpad-Cloud-SDK && pip3 install --user -r requirements.txt && ./setup.py install --user && popd
  script:
    - cd Thinpad-Cloud-SDK
    - ./example.py "$THINPAD_CLOUD_USER" "$THINPAD_CLOUD_PASSWD" ../thinpad_top.runs/impl_1/thinpad_top.bit
