variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

bitstream:
  stage: build
  image: vivado2019:2019.2-mips-gcc
  script:
    - env
    - /opt/Xilinx/Vivado/2019.2/bin/vivado -mode tcl -source .ci-scripts/bits.tcl thinpad_top.xpr
    - test -f thinpad_top.runs/impl_1/*.bit

  artifacts:
    paths:
      - thinpad_top.runs/impl_1/*.bit
      - thinpad_top.runs/*/runme.log

